services:
  app:
    container_name: base-express-auth
    build: ./base-express-auth
    ports:
      - "5000:5000"
    env_file:
      - base-express-auth/.env
    volumes:
      - ./base-express-auth:/server  # Maps app folder correctly
    restart: unless-stopped
    depends_on:
      - mongo

  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root  # ✅ Correct username
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword  # ✅ Correct password
      ME_CONFIG_MONGODB_URL: mongodb://root:rootpassword@mongodb:27017/  # ✅ Correct MongoDB URL

volumes:
  mongo_data:
